CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE TABLE skills (
        skill_id integer GENERATED BY DEFAULT AS IDENTITY,
        skill_name character varying(100) NOT NULL,
        description text,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_skills" PRIMARY KEY (skill_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE TABLE users (
        user_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(255) NOT NULL,
        email character varying(255) NOT NULL,
        phone character varying(50),
        password_hash character varying(255) NOT NULL,
        role character varying(50) NOT NULL DEFAULT 'Member',
        monthly_limit integer,
        device_token text,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_users" PRIMARY KEY (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE TABLE tasks (
        task_id integer GENERATED BY DEFAULT AS IDENTITY,
        task_name character varying(255) NOT NULL,
        frequency character varying(50) NOT NULL,
        day_rule character varying(50) NOT NULL,
        required_skill_id integer,
        is_restricted boolean NOT NULL DEFAULT FALSE,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_tasks" PRIMARY KEY (task_id),
        CONSTRAINT "FK_tasks_skills_required_skill_id" FOREIGN KEY (required_skill_id) REFERENCES skills (skill_id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE TABLE user_skills (
        user_id integer NOT NULL,
        skill_id integer NOT NULL,
        assigned_date timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_user_skills" PRIMARY KEY (user_id, skill_id),
        CONSTRAINT "FK_user_skills_skills_skill_id" FOREIGN KEY (skill_id) REFERENCES skills (skill_id) ON DELETE CASCADE,
        CONSTRAINT "FK_user_skills_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE TABLE assignments (
        assignment_id integer GENERATED BY DEFAULT AS IDENTITY,
        task_id integer NOT NULL,
        user_id integer NOT NULL,
        event_date timestamp with time zone NOT NULL,
        status character varying(50) NOT NULL DEFAULT 'Pending',
        rejection_reason text,
        is_override boolean NOT NULL DEFAULT FALSE,
        assigned_by integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_assignments" PRIMARY KEY (assignment_id),
        CONSTRAINT "FK_assignments_tasks_task_id" FOREIGN KEY (task_id) REFERENCES tasks (task_id) ON DELETE CASCADE,
        CONSTRAINT "FK_assignments_users_assigned_by" FOREIGN KEY (assigned_by) REFERENCES users (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_assignments_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (1, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can lead Tuesday Bible Study sessions', TRUE, 'CanLeadBibleStudy', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (2, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can lead Sunday Preaching and deliver sermons', TRUE, 'CanLeadPreaching', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (3, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can lead prayer sessions', TRUE, 'CanLeadPrayer', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (4, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can make church announcements', TRUE, 'CanMakeAnnouncements', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (5, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can lead worship and praise sessions', TRUE, 'CanLeadWorship', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (6, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can operate sound and audio equipment', TRUE, 'CanOperateSound', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO skills (skill_id, created_at, description, is_active, skill_name, updated_at)
    VALUES (7, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Can manage children''s ministry', TRUE, 'CanManageChildren', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, required_skill_id, task_name, updated_at)
    VALUES (2, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Tuesday', 'Weekly', TRUE, NULL, 'Lead Prayer Meeting', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, required_skill_id, task_name, updated_at)
    VALUES (4, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Sunday', 'Weekly', TRUE, NULL, 'Lead Opening Prayer', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, required_skill_id, task_name, updated_at)
    VALUES (5, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Sunday', 'Weekly', TRUE, NULL, 'Lead Announcements', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, required_skill_id, task_name, updated_at)
    VALUES (6, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Sunday', 'Weekly', TRUE, NULL, 'Lead Closing Prayer', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, required_skill_id, task_name, updated_at)
    VALUES (7, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Last Friday', 'Monthly', TRUE, NULL, 'Lead All-Night Prayer', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, required_skill_id, task_name, updated_at)
    VALUES (8, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Last Saturday', 'Monthly', TRUE, NULL, 'Lead Vigil Prayer', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    INSERT INTO users (user_id, created_at, device_token, email, is_active, monthly_limit, name, password_hash, phone, role, updated_at)
    VALUES (1, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, 'admin@church.com', TRUE, NULL, 'System Administrator', '$2a$11$YourBCryptHashHere', '+1234567890', 'Admin', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, is_restricted, required_skill_id, task_name, updated_at)
    VALUES (1, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Tuesday', 'Weekly', TRUE, TRUE, 1, 'Lead Bible Study', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO tasks (task_id, created_at, day_rule, frequency, is_active, is_restricted, required_skill_id, task_name, updated_at)
    VALUES (3, TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Sunday', 'Weekly', TRUE, TRUE, 2, 'Lead Preaching', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_assignments_event_date ON assignments (event_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_assignments_status ON assignments (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_assignments_task ON assignments (task_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_assignments_user_date ON assignments (user_id, event_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX "IX_assignments_assigned_by" ON assignments (assigned_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE UNIQUE INDEX idx_skills_name ON skills (skill_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_tasks_frequency ON tasks (frequency);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_tasks_skill ON tasks (required_skill_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_user_skills_skill ON user_skills (skill_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_user_skills_user ON user_skills (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE UNIQUE INDEX idx_users_email ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    CREATE INDEX idx_users_role ON users (role);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('skills', 'skill_id'),
        GREATEST(
            (SELECT MAX(skill_id) FROM skills) + 1,
            nextval(pg_get_serial_sequence('skills', 'skill_id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('tasks', 'task_id'),
        GREATEST(
            (SELECT MAX(task_id) FROM tasks) + 1,
            nextval(pg_get_serial_sequence('tasks', 'task_id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('users', 'user_id'),
        GREATEST(
            (SELECT MAX(user_id) FROM users) + 1,
            nextval(pg_get_serial_sequence('users', 'user_id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331182609_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260331182609_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331190339_UpdateAdminPassword') THEN
    UPDATE users SET password_hash = '$2a$11$vZXm0xt/6JqZp4N0a2wVYO3h0i2EyKxGQ0rN0MqRXqB6Kd9Y3qH8G'
    WHERE user_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260331190339_UpdateAdminPassword') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260331190339_UpdateAdminPassword', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    CREATE TABLE invitations (
        invitation_id integer GENERATED BY DEFAULT AS IDENTITY,
        email character varying(255) NOT NULL,
        name character varying(255) NOT NULL,
        phone character varying(50) NOT NULL,
        role character varying(50) NOT NULL DEFAULT 'Member',
        token character varying(255) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        expires_at timestamp with time zone NOT NULL,
        is_used boolean NOT NULL DEFAULT FALSE,
        used_at timestamp with time zone,
        user_id integer,
        created_by integer NOT NULL,
        CONSTRAINT "PK_invitations" PRIMARY KEY (invitation_id),
        CONSTRAINT "FK_invitations_users_created_by" FOREIGN KEY (created_by) REFERENCES users (user_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_invitations_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    UPDATE users SET password_hash = '$2a$11$X6qGvzOj1Xd/sOJs.rc0FOxxoda66NVWgoIHi.VkPTy2XRlzAlOJm'
    WHERE user_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    CREATE INDEX idx_invitations_email ON invitations (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    CREATE INDEX idx_invitations_is_used ON invitations (is_used);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    CREATE UNIQUE INDEX idx_invitations_token ON invitations (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    CREATE INDEX "IX_invitations_created_by" ON invitations (created_by);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    CREATE INDEX "IX_invitations_user_id" ON invitations (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260401200850_AddInvitationSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260401200850_AddInvitationSystem', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    DROP INDEX idx_users_email;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    DROP INDEX idx_skills_name;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    DROP INDEX idx_invitations_email;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE users ADD tenant_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE user_skills ADD tenant_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE tasks ADD tenant_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE skills ADD tenant_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE invitations ADD tenant_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE assignments ADD tenant_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE TABLE tenants (
        tenant_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(255) NOT NULL,
        slug character varying(100) NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        contact_email character varying(255) NOT NULL,
        subscription_end_date timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tenants" PRIMARY KEY (tenant_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE skills SET tenant_id = 1
    WHERE skill_id = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE tasks SET tenant_id = 1
    WHERE task_id = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    INSERT INTO tenants (tenant_id, contact_email, created_at, is_active, name, slug, subscription_end_date)
    VALUES (1, 'admin@church.com', TIMESTAMPTZ '2026-01-01T00:00:00Z', TRUE, 'Default Church', 'default-church', TIMESTAMPTZ '2036-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    UPDATE users SET tenant_id = 1
    WHERE user_id = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE UNIQUE INDEX idx_users_tenant_email ON users (tenant_id, email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE INDEX "IX_user_skills_tenant_id" ON user_skills (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE INDEX "IX_tasks_tenant_id" ON tasks (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE UNIQUE INDEX idx_skills_tenant_name ON skills (tenant_id, skill_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE INDEX idx_invitations_tenant_email ON invitations (tenant_id, email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE INDEX "IX_assignments_tenant_id" ON assignments (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    CREATE UNIQUE INDEX idx_tenants_slug ON tenants (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE assignments ADD CONSTRAINT "FK_assignments_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE invitations ADD CONSTRAINT "FK_invitations_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE skills ADD CONSTRAINT "FK_skills_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE tasks ADD CONSTRAINT "FK_tasks_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE user_skills ADD CONSTRAINT "FK_user_skills_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    ALTER TABLE users ADD CONSTRAINT "FK_users_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    PERFORM setval(
        pg_get_serial_sequence('tenants', 'tenant_id'),
        GREATEST(
            (SELECT MAX(tenant_id) FROM tenants) + 1,
            nextval(pg_get_serial_sequence('tenants', 'tenant_id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260406052347_AddMultiTenancy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260406052347_AddMultiTenancy', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE TABLE roster_proposals (
        proposal_id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        name character varying(255) NOT NULL,
        status character varying(50) NOT NULL DEFAULT 'Processing',
        date_range_start date NOT NULL,
        date_range_end date NOT NULL,
        generated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        published_at timestamp with time zone,
        created_by_user_id integer NOT NULL,
        CONSTRAINT "PK_roster_proposals" PRIMARY KEY (proposal_id),
        CONSTRAINT "FK_roster_proposals_tenants_tenant_id" FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_roster_proposals_users_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE TABLE proposal_skip_logs (
        log_id integer GENERATED BY DEFAULT AS IDENTITY,
        proposal_id integer NOT NULL,
        task_id integer NOT NULL,
        event_date date NOT NULL,
        reason text NOT NULL,
        logged_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_proposal_skip_logs" PRIMARY KEY (log_id),
        CONSTRAINT "FK_proposal_skip_logs_roster_proposals_proposal_id" FOREIGN KEY (proposal_id) REFERENCES roster_proposals (proposal_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE TABLE roster_proposal_items (
        item_id integer GENERATED BY DEFAULT AS IDENTITY,
        proposal_id integer NOT NULL,
        task_id integer NOT NULL,
        user_id integer NOT NULL,
        event_date date NOT NULL,
        status character varying(50) NOT NULL DEFAULT 'Proposed',
        skip_reason text,
        CONSTRAINT "PK_roster_proposal_items" PRIMARY KEY (item_id),
        CONSTRAINT "FK_roster_proposal_items_roster_proposals_proposal_id" FOREIGN KEY (proposal_id) REFERENCES roster_proposals (proposal_id) ON DELETE CASCADE,
        CONSTRAINT "FK_roster_proposal_items_tasks_task_id" FOREIGN KEY (task_id) REFERENCES tasks (task_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_roster_proposal_items_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX idx_skip_logs_proposal ON proposal_skip_logs (proposal_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX idx_proposal_items_proposal ON roster_proposal_items (proposal_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX "IX_roster_proposal_items_task_id" ON roster_proposal_items (task_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX "IX_roster_proposal_items_user_id" ON roster_proposal_items (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX idx_roster_proposals_tenant ON roster_proposals (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX idx_roster_proposals_tenant_status ON roster_proposals (tenant_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    CREATE INDEX "IX_roster_proposals_created_by_user_id" ON roster_proposals (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260410064601_AddProposalModule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260410064601_AddProposalModule', '10.0.0');
    END IF;
END $EF$;
COMMIT;

