-- =============================================
-- Church Ministry Rostering System
-- Seed Data Script
-- Version: 1.0
-- =============================================

-- =============================================
-- Seed Skills
-- =============================================
INSERT INTO skills (skill_name, description) VALUES
('CanLeadBibleStudy', 'Can lead Tuesday Bible Study sessions'),
('CanLeadPreaching', 'Can lead Sunday Preaching and deliver sermons'),
('CanLeadPrayer', 'Can lead prayer sessions'),
('CanMakeAnnouncements', 'Can make church announcements'),
('CanLeadWorship', 'Can lead worship and praise sessions'),
('CanOperateSound', 'Can operate sound and audio equipment'),
('CanManageChildren', 'Can manage children''s ministry');

-- =============================================
-- Seed Default Tasks
-- Based on Development Guide requirements
-- =============================================

-- Weekly Tasks - Tuesday
INSERT INTO tasks (task_name, frequency, day_rule, required_skill_id, is_restricted) VALUES
('Lead Bible Study', 'Weekly', 'Tuesday', (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadBibleStudy'), TRUE),
('Lead Prayer Meeting', 'Weekly', 'Tuesday', NULL, FALSE);

-- Weekly Tasks - Sunday
INSERT INTO tasks (task_name, frequency, day_rule, required_skill_id, is_restricted) VALUES
('Lead Preaching', 'Weekly', 'Sunday', (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadPreaching'), TRUE),
('Lead Opening Prayer', 'Weekly', 'Sunday', NULL, FALSE),
('Lead Announcements', 'Weekly', 'Sunday', NULL, FALSE),
('Lead Closing Prayer', 'Weekly', 'Sunday', NULL, FALSE);

-- Monthly Tasks
INSERT INTO tasks (task_name, frequency, day_rule, required_skill_id, is_restricted) VALUES
('Lead All-Night Prayer', 'Monthly', 'Last Friday', NULL, FALSE),
('Lead Vigil Prayer', 'Monthly', 'Last Saturday', NULL, FALSE);

-- =============================================
-- Seed Default Admin User
-- Password: Admin@123 (hashed with BCrypt)
-- NOTE: Change this password immediately after first login!
-- =============================================
INSERT INTO users (name, email, phone, password_hash, role, is_active) VALUES
('System Administrator', 'admin@church.com', '+1234567890', 
 '$2a$11$YourBCryptHashHere', -- This is a placeholder - will be generated by backend
 'Admin', TRUE);

-- =============================================
-- Seed Sample Members (Optional - for testing)
-- =============================================
-- Uncomment below to create sample test members

/*
INSERT INTO users (name, email, phone, password_hash, role, monthly_limit, is_active) VALUES
('John Doe', 'john.doe@church.com', '+1234567891', '$2a$11$SampleHash1', 'Member', 4, TRUE),
('Jane Smith', 'jane.smith@church.com', '+1234567892', '$2a$11$SampleHash2', 'Member', 4, TRUE),
('Robert Johnson', 'robert.j@church.com', '+1234567893', '$2a$11$SampleHash3', 'Member', 4, TRUE),
('Mary Williams', 'mary.w@church.com', '+1234567894', '$2a$11$SampleHash4', 'Member', 4, TRUE),
('David Brown', 'david.b@church.com', '+1234567895', '$2a$11$SampleHash5', 'Member', 4, TRUE);

-- Assign skills to sample members
INSERT INTO user_skills (user_id, skill_id) VALUES
((SELECT user_id FROM users WHERE email = 'john.doe@church.com'), (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadBibleStudy')),
((SELECT user_id FROM users WHERE email = 'john.doe@church.com'), (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadPrayer')),
((SELECT user_id FROM users WHERE email = 'jane.smith@church.com'), (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadPreaching')),
((SELECT user_id FROM users WHERE email = 'jane.smith@church.com'), (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadPrayer')),
((SELECT user_id FROM users WHERE email = 'robert.j@church.com'), (SELECT skill_id FROM skills WHERE skill_name = 'CanLeadPrayer'));
*/

-- =============================================
-- Verification Queries
-- =============================================

-- Verify skills were created
SELECT * FROM skills ORDER BY skill_id;

-- Verify tasks were created
SELECT t.task_id, t.task_name, t.frequency, t.day_rule, 
       s.skill_name, t.is_restricted
FROM tasks t
LEFT JOIN skills s ON t.required_skill_id = s.skill_id
ORDER BY t.task_id;

-- Verify admin user was created
SELECT user_id, name, email, role FROM users WHERE role = 'Admin';

-- =============================================
-- Seed Data Complete
-- =============================================
